name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Updating package.json version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Updating package.json version to VERSION"
          npm version ${VERSION}

      - name: Commit package.json
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m "chore: version bump to ${VERSION}"

      - name: Create tag
        run: |
          git tag "${VERSION}"
          git push origin --tags

      - name: Creating release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: "Release ${{ github.event.inputs.version }} created automatically"
          draft: false
          prerelease: false

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

