name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Updating package.json version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Updating package.json version to ${VERSION}"
          jq ".version = \"${VERSION}\"" package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Commit package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: version bump to ${{ github.event.inputs.version }}"
          git push origin HEAD

      - name: Create tag
        run: |
          VERSION=${{ github.event.inputs.version }}
          git tag "v${VERSION}"
          git push origin --tags

      - name: Creating release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: "Release v${{ github.event.inputs.version }} created automatically"
          draft: false
          prerelease: false

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

